title: Regalis Societas Tokyo
description: "日本の伝統と匠の技に裏打ちされた、世界に通用するモダンなラグジュアリーオーダースーツブランド。"
url: "https://kanta02cer.github.io"
baseurl: "/regalis-hp"

include:
  - images
  - open.anim.mp4

# Triggering new build to clear cache
